spring.application.name=todo-app

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/todo
spring.datasource.username=postgres
spring.datasource.password=Postgre@Atul2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
